library(shiny)
library(dygraphs)
shinyUI(
  fluidPage(
    fluidRow(
      column(3,
             uiOutput("headerlUI1")
      ),
      column(3,
             uiOutput("headerlUI2")
      ),
      column(3,
             uiOutput("headerlUI3")
      ),
      column(3,
             uiOutput("headerlUI4")
      )
    ),
    fluidRow(
      column(3,
             uiOutput("navbarUI1")
      ),
      column(3,
             uiOutput("navbarUI2")
      ),
      column(3,
             uiOutput("navbarUI3")
      ),
      column(3,
             uiOutput("navbarUI4")
      )
    ),
    fluidRow(
      fluidRow(
        column(12,
               uiOutput("mainpanelUI")
        )
      ),
      fluidRow(
        column(12,
               uiOutput("mainpanenavUI1")
        )
      ),
      fluidRow(
        column(12,
               uiOutput("mainpanenavUI2")
        )
      ),
      fluidRow(
        column(12,
               uiOutput("mainpanenavUI3")
        )
      ),
      fluidRow(
        column(12,
               uiOutput("mainpanenavUI4")
        )
      )
    ),
    fluidRow(
      column(12,
             uiOutput("footerUI")
      )
    )
  )
)
